image: python:3.10-slim-buster  
stages:
  - fetch

fetch_medium:
  stage: fetch
  before_script:
    - apt-get update
    - apt-get install -y libpq-dev gcc
  script:
    - pip install -r requirements.txt
    - python fetch_data.py
  rules:
    - when: manual
